resources:
- name: flight-school
  type: git
  source:
    uri: https://github.com/kc1516/concourse
    branch: master

jobs:
- name: test-app
  plan:
  - get: flight-school
    trigger: true
  - task: tests
    file: flight-school/build.yml
